stages:
    - npm build
    - AddToStorage
npm_build:
   image: node:18.12.1
   stage: npm build
   before_script:
     - npm ci  
   script: 
     - npm run build
   variables:
    array: "(Get-Childitem -Path /public )" 
   only:
   - features-New_CI  
AddToStorage:
  stage: AddToStorage
  script:  
    - foreach ($item in $array){ aws --endpoint-url=https://storage.yandexcloud.net/ws-admin-fe-ci s3 cp $item s3://}  
  only:
  - features-New_CI