stages:
    - build
build_image:
 image: docker:latest
 stage: build
 variables:
   DOCKER_DRIVER: overlay2
   DOCKER_TLS_CERDIR: ""
   DOCKER_HOST: tcp://localhost:2375/
 services:
   - docker:18.09-dind
 before_script:
 - docker login -u oauth -p $OAUTH cr.yandex
 script:
 - docker build . -t cr.yandex/$REGISTRYID/test:1 
 - docker push cr.yandex/$REGISTRYID/test:1
  
