stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   cache:
    paths:
      - build/
   before_script:
     - npm ci   
     - npm run build   
   script:  
      - cd build
      - ls
      - pwsh ./ AddToStorage.ps1
