build_image:
 script:
 - docker login \
  --username oauth \
  --password y0_AgAEA7qkTKO0AATuwQAAAADV-oZRJo06kGQFTEa2u6WfAbDTpE9XWD4 \
  cr.yandex
 - docker build . \
  -t cr.yandex/crpfu9m3bepjcshqiu65/test:1
 - docker push cr.yandex/crpfu9m3bepjcshqiu65/test:1
  
