stages:
    - npm build
    - deploy
deploy to s3:
  stage: deploy
  image: banct/awscli
  script:
   - ls
npm_build:
   image: node:18.12.1
   stage: npm build
   cache:
    paths:
      - build/
   before_script:
     - npm ci
   script:
      - npm run build   
      - ls
      - Get-Location
