stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   cache:
    paths:
      - build/
   before_script:
     - npm ci
     - npm run build   
   script:  
      - cd build
      - ls
      - aws --endpoint-url=https://storage.yandexcloud.net/ws-admin-fe-ci s3 cp --recursive ./ s3://ws-admin-fe-ci
      