stages:
    - npm build
    - deploy
deploy to s3:
  stage: deploy
  image: banct/awscli
  script:
   - ls
npm_build:
   image: node:18.12.1
   stage: npm build
   before_script:
     - npm ci
   script:
      - npm run build   
      - ls
      - Get-Location
      - Copy-Item -Path "C:\GitLab-Runner\builds\g-MKDXB7\0\wscloud\wsfe\build" -Destination "C:\GitLab-Runner\builds\g-MKDXB7\0\wscloud\wsfe"
