stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   cache:
    paths:
      - build/
   before_script:
     - npm ci
   script:
      - npm run build   
      - cd build
      - ls
      - aws configure
      - YCAJEoTenIl63IUD51g2e2_U1
      - YCMRAH7b5ogCCZubwXIGQHl6xqdT9HYslD_W7FSY
      - ru-central1
      - None
      - aws --endpoint-url=https://storage.yandexcloud.net/stan-eto-na-vremya s3 cp --recursive ./ s3://stan-eto-na-vremya
      