stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   variables:
    $array: "@(Get-Childitem -Path .  )" 
   before_script:
     - npm ci   
     - npm run build   
   script:  
    - cd build
    - ls
    - foreach ($item in $array){ aws --endpoint-url=https://storage.yandexcloud.net/ws-admin-fe-ci s3 cp $item s3://}

