stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   before_script:
     - npm ci  
     - npm run build
   script: 
     - cd build
     - ls 
     - aws --endpoint-url=https://storage.yandexcloud.net/ s3 cp --recursive ./ s3://ws-admin-fe-ci/
   only:
   - features-New_CI  

