stages:
    - build
build_image:
 image: docker:latest
 stage: build
 variables:
   DOCKER_DRIVER: overlay2
   DOCKER_TLS_CERDIR: ""
   DOCKER_HOST: tcp://localhost:2375/
 services:
   - docker:19.03.0-dind
 before_script:
 - docker login -u oauth -p y0_AgAEA7qkTKO0AATuwQAAAADV-oZRJo06kGQFTEa2u6WfAbDTpE9XWD4 cr.yandex
 script:
 - docker build . -t cr.yandex/crpfu9m3bepjcshqiu65/test:1 
 - docker push cr.yandex/crpfu9m3bepjcshqiu65/test:1
  
