stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   cache:
    paths:
      - build/
   before_script:
     - npm ci
   script:
      - npm run build   
      - cd build
      - ls
      - aws --endpoint-url=https://storage.yandexcloud.net/admin-dev.wscloud.pro \
       s3 cp --recursive ./ s3://admin-dev.wscloud.pro
      