stages:
    - npm build
npm_build:
   image: node:18.12.1
   stage: npm build
   before_script:
     - npm ci  
     - npm run build
   script: 
     - cd build
     - ls
     - foreach ($item in Get-ChildItem . -Name){ aws --endpoint-url=https://storage.yandexcloud.net/ws-admin-fe-ci s3 cp $item s3://}  
   only:
   - features-New_CI  

